name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '0 0 */2 * *' # Every 2 days
  workflow_dispatch:      # Manually test.

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Real User Visit
        run: |
          curl -sA "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" https://nattawut-blsc.streamlit.app/
