name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '0 0 */3 * *' # รันทุก 3 วัน
  workflow_dispatch:      # ปุ่มกดรันเองเพื่อทดสอบ

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Real User Visit
        run: |
          curl -sA "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" https://nattawut-blsc.streamlit.app/
